//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Based_Task_Manger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist
    {
        public int Checklist_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Item_name { get; set; }
        public Nullable<int> Item_priority { get; set; }
        public string Item_status { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Comments { get; set; }
        public System.DateTime Created_at { get; set; }
        public System.DateTime Updated_at { get; set; }
        public Nullable<int> Task_ID { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
