//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Based_Task_Manger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class web_task_managerDBEntities : DbContext
    {
        public web_task_managerDBEntities()
            : base("name=web_task_managerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checklist> Checklists { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Dashboard> Dashboards { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<SearchFilter> SearchFilters { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Task_Assignment> Task_Assignments { get; set; }
        public virtual DbSet<Task_Member> Task_Members { get; set; }
        public virtual DbSet<TimeTracker> TimeTrackers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
