//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Based_Task_Manger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Notifications_ID { get; set; }
        public Nullable<int> Task_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Message { get; set; }
        public System.DateTime Created_at { get; set; }
        public System.DateTime Updated_at { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
