//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Based_Task_Manger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchFilter
    {
        public int SearchFilter_ID { get; set; }
        public string Search_term { get; set; }
        public string Results { get; set; }
        public string Filter_name { get; set; }
        public string Filter_Criteria { get; set; }
        public string Recommendation { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
